#班级表
DROP TABLE "CLASS";

CREATE TABLE "CLASS" (
  "CLASSID" INTEGER IDENTITY(1,1) NOT NULL,
  "CLASSNAME" VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY ("CLASSID")
);

INSERT INTO "CLASS" ("CLASSID", "CLASSNAME") VALUES (1,'一班');
INSERT INTO "CLASS" ("CLASSID", "CLASSNAME") VALUES (2,'二班');

#映射表
DROP TABLE "CLASSROOM";

CREATE TABLE "CLASSROOM" (
  "ID" INT IDENTITY(1,1) NOT NULL,
  "CLASS_ID" INT DEFAULT NULL,
  "STUDENT_ID" INT DEFAULT NULL,
  PRIMARY KEY ("ID")
);


INSERT INTO "CLASSROOM" ("ID", "CLASS_ID", "STUDENT_ID") VALUES (1,1,1);
INSERT INTO "CLASSROOM" ("ID", "CLASS_ID", "STUDENT_ID") VALUES (2,1,2);
INSERT INTO "CLASSROOM" ("ID", "CLASS_ID", "STUDENT_ID") VALUES (3,2,3);
INSERT INTO "CLASSROOM" ("ID", "CLASS_ID", "STUDENT_ID") VALUES (4,2,4);

#学生表
DROP TABLE "STUDENT";
CREATE TABLE "STUDENT" (
  "ID" INT IDENTITY(1,1) NOT NULL,
  "NAME" VARCHAR(200) DEFAULT NULL,
  "AGE" TINYINT DEFAULT NULL,
  PRIMARY KEY ("ID")
);


INSERT INTO "STUDENT" ("NAME", "AGE") VALUES ('点点',16);
INSERT INTO "STUDENT" ("NAME", "AGE") VALUES ('平平',16);
INSERT INTO "STUDENT" ("NAME", "AGE") VALUES ('美美',16);
INSERT INTO "STUDENT" ("NAME", "AGE") VALUES ('团团',16);

#测试表
CREATE TABLE E_CANCEL
(
       S_EXT_NODENUM          VARCHAR(40) NOT NULL,
       PRIPID                 VARCHAR(36),
       CANREA                 VARCHAR(1000),
       CANDATE                DATETIME,
       CANAUTH                VARCHAR(500),
       SANDOCNO               VARCHAR(50),
       PUBNEWSNAME            VARCHAR(100),
       PUBDATE                DATETIME,
       EXTCLEBRSIGN           VARCHAR(1),
       CANCELBRSIGN           VARCHAR(1),
       DECLEBRSIGN            VARCHAR(1),
       AFFWRITNO              VARCHAR(50),
       BLICREVORINUM          NUMERIC(20,0),
       BLICREVORINO           VARCHAR(36),
       BLICREVDUPCONUM        NUMERIC(20,0),
       CAREVNUM               NUMERIC(20,0),
       CAREVST                VARCHAR(255),
       S_EXT_TIMESTAMP        DATETIME,
       S_EXT_BATCH            VARCHAR(40),
       S_EXT_SEQUENCE         VARCHAR(32) NOT NULL,
       S_EXT_VALIDFLAG        VARCHAR(1),
       S_EXT_ICODE            VARCHAR(128),
       S_EXT_CODETIME         DATETIME,
       PRIMARY KEY(S_EXT_NODENUM,S_EXT_SEQUENCE)
);
COMMENT ON TABLE E_CANCEL IS '测试用CANCEL表';

-- Create Index --
CREATE INDEX IND_E_CANCEL_01 ON E_CANCEL("S_EXT_NODENUM","S_EXT_VALIDFLAG" DESC,"S_EXT_TIMESTAMP") INDEXTYPE IS BTREE LOCAL;
CREATE INDEX IND_E_CANCEL_PRIPID ON E_CANCEL("S_EXT_NODENUM","PRIPID","S_EXT_VALIDFLAG" DESC) INDEXTYPE IS BTREE LOCAL;

